### ISSUE TITLE
Extract the raw text corpus from your mother tongue Wikipedia chapter

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#1]
Run step 1.i of the workflow, as per the [README](../blob/master/README.md#high-level-workflow--related-code).
You should review the related script (especially [these lines](../blob/master/extract_verbs.sh#L6-L11)), polish it and update it accordingly.  
**Heads-up!**
Make the script more robust by letting the user provide the ~~Wikipedia dump URL~~ *language* as a command line argument (like `it` or `italian` for Italian)

**Comment by kkasunperera** [comment]
@marfox I have made a pull request for this issue https://github.com/dbpedia/fact-extractor/pull/4 pls check

**Comment by marfox** [comment]
Given the language, the script should pick the right Wikipedia dump and the right TreeTagger instance

**Comment by kkasunperera** [comment]
@marfox I'm getting this error when running the "extract_verbs.sh" this line
"cat extracted/*/* | csplit --suppress-matched -z -f 'corpus/doc_' - '/</doc>/' {*}"
https://github.com/dbpedia/fact-extractor/blob/master/extract_verbs.sh#L11

error- 
csplit: unrecognized option '--suppress-matched'
Try `csplit --help' for more information.

In documentation I couldn't find any option "--suppress-matched". Can you please provide any hint to resolve this?

**Comment by marfox** [comment]
You need csplit (GNU coreutils) 8.23 for that
