### ISSUE TITLE
Build a list of relation candidates that do not currently exist in DBpedia

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#24]
## DISCLAIMER: this issue is not related to code

We want to assess the potential of the fact extractor.
Try to address the following question:
> Which relations can we extract that are not already mapped in the [DBpedia ontology](http://mappings.dbpedia.org/server/ontology/classes/) or do not exist in the [raw infobox properties](http://wiki.dbpedia.org/Downloads2014#h407-1) datasets?

- Focus on the **soccer** domain in your **mother tongue**;
- Build a list of potentially interesting relations that are not already in the corresponding DBpedia chapter;
- Compute statistics by browsing through soccer-related DBpedia entities, i.e., instances of *SoccerPlayer*, *SoccerClub*, *SoccerManager*, *SoccerLeague*, *SoccerTournament*, *SoccerLeagueSeason*.

#### DBpedia magic
The following *SPARQL* query computes the amount of raw infobox properties for a given `$CLASS`. You can fire it to your DBpedia language endpoint
```
SELECT DISTINCT(?properties), (count(?properties) as ?amount)
WHERE
{
  ?s a <http://dbpedia.org/ontology/$CLASS> ;
    ?properties ?o .
  FILTER (regex(?properties, "dbpedia.org/property"))
}
ORDER BY ?amount
```

#### Bonus
Can you figure out the query for the **ontology** properties?

**Comment by fsonntag** [comment]
Also a question about this task: I came up with a few ideas and I think I solved the bonus question. The task seems to be asked quite open, should I post my thoughts here or in the application?

**Comment by marfox** [comment]
Feel free to post an informal recap of your thoughts here while working 
on your application on melange. The sooner you upload something there, 
the better feedback you will get.
Cheers!

**Comment by fsonntag** [comment]
Thanks for the answer!
Some things I think are missing:
* Incidents between soccer players, e.g. Oliver Kahn grabbed Thomas Brdarić by the the neck or he almot bit Heiko Herrlich. Both are written down in the German wikipedia.
* A breakdown of the played games. How many games during his time at Arsenal London was Mesut Özil not allowed to play (maybe even the reason: injury, lack of performance)? There is a dbpedia-owl:numberOfMatches in his carrerStations, but I think there must me more information.

Also due to looking at Kicktionary data, the information about matches and their scenes are not represented. It would be interesting to look up previous one on one situations b/w two players. But I'm not sure if one can get this information from Wikipedia, as it is quite specific.

And the solution about the bonus question should be:
```
SELECT DISTINCT(?properties), (count(?properties) as ?amount)
WHERE
{
  ?s a <http://dbpedia.org/ontology/$CLASS> ;
    ?properties ?o .
  FILTER (regex(?properties, "dbpedia.org/ontology"))
}
ORDER BY ?amount
```

**Comment by kkasunperera** [comment]
@marfox these are some of the interesting relationships that came to my mind, what is your idea on those?

For the "SoccerPlayer"

"InjuriesSuffered" 
Having suffered a string of serious injuries throughout his career, Ronaldo retired on 14 February 2011, citing pain and hypothyroidism as the reasons for his premature retirement  source-http://en.wikipedia.org/wiki/Ronaldo

"StyleOfPlay"
Maradona was renowned for his dribbling ability, vision, close ball control, passing and creativity, and is considered one of the most skillful players ever. source-http://en.wikipedia.org/wiki/Diego_Maradona

**Comment by marfox** [comment]
On 3/23/15 6:44 PM, Felix Sonntag wrote:
> Thanks for the answer!
> Some things I think are missing:
Missing where? In this project or in the DBpedia ontology?
>
>   * Incidents between soccer players, e.g. Oliver Kahn grabbed Thomas
>     Brdarić by the the neck or he almot bit Heiko Herrlich. Both are
>     written down in the German wikipedia.
>   * A breakdown of the played games. How many games during his time at
>     Arsenal London was Mesut Özil not allowed to play (maybe even the
>     reason: injury, lack of performance)? There is a
>     dbpedia-owl:numberOfMatches in his carrerStations, but I think there
>     must me more information.
>
> Also due to looking at Kicktionary data, the information about matches
> and their scenes are not represented.
Kicktionary was actually made for understanding the football match 
reports. That's why you can find those specific frames there.
> It would be interesting to look up
> previous one on one situations b/w two players. But I'm not sure if one
> can get this information from Wikipedia, as it is quite specific.
You got it, I'm not sure whether those frames can be applied to the 
Wikipedia corpus.
You can always add an analysis on that in your GSoC proposal, that would 
be interesting.
>
> And the solution about the bonus question should be:
>
> |SELECT DISTINCT(?properties), (count(?properties) as ?amount)
> WHERE
> {
>    ?s a <http://dbpedia.org/ontology/$CLASS> ;
>      ?properties ?o .
>    FILTER (regex(?properties, "dbpedia.org/ontology"))
> }
> ORDER BY ?amount
Good catch @fsonntag! It was not so hard right? :-)

**Comment by marfox** [comment]
Can you support those with some robust corpus evidence, e.g., how many 
Wikipedia articles and which LUs may trigger them?

**Comment by fsonntag** [comment]
> Missing where? In this project or in the DBpedia ontology?
Missing in the ontology as well in the raw infobox properties.

Anyway more about the injuries of soccer players by @kkasunperera , as I think it's quite a decent example to evaluate.
After inspecting the wikipedia article of 10,000 football players, I could find, that there is information about injuries in over 1,000 of the Wikipedia articles, just by looking for the count of the substring "injur". I know, this is not a mature approach, but it already gives a clue about the possibilities. 
To be precise, 9,978 of the 10,000 football players had a Wikipedia article. Split up by the number of occurrences of the substring "injur" in each article, gives us the following statistics, showing that there's information in over 11% of the articles about injuries.

Num occurences | Num articles
------ | ------
0 | 8798
1 | 727
2 | 235
3 | 96
4 | 40
5 | 33
6 | 14
7 | 10
8 | 7
9 | 3
10 | 5
11 | 3
14 | 1
15 | 2
18 | 1

Another example would be (the year of) retirement. While this info is present in very few infoboxes (3), this information cannot be found in the ontology.
Doing the same approach like above, just with the substring "retire", gives the following statistics, showing that there's information in over 13% of the articles about retirement.

Num occurences | Num articles
------ | ------
0 | 8651
1 | 1037
2 | 231
3 | 41
4 | 13
5 | 4
6 | 1

Considering that most articles about SoccerPlayers are really short and most of these SoccerPlayers are not really relevant, I think these additional information can have a great use in DBPedia.
