### ISSUE TITLE
Map Frame Extraction results to the RDF data model

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#25]
## DISCLAIMER: this issue is not related to code

The final objective of the fact extractor is to produce statements for DBpedia.
Hence, we need a model that maps the results of the frame extraction step into the RDF data model.
The classification results format is the same as [the training data one](../blob/master/resources/training-data.sample).

Can you think of the less verbose way to represent them as RDF statements? This would be a great addition for your GSoC proposal.

**Comment by fsonntag** [comment]
Hi Marco,

I'm interested in picking up this task as a warmup for GSoC.
But can you please help to clarify the meaning of each column. I couldn't find a documentation.
Here is my guess:
* Sentence ID
* Index of word in sentence
* Word
* POS-Tag
* Lemma of the word
* Topic of the sentence
* Frame element

**Comment by fsonntag** [comment]
So I gave that issue a few thoughts. RDF itself is quite verbose compared to the showed training data. 
Anyway I think the Turtle format is the best way of representation. XML obviously is really verbose, JSON-LD not nearly as verbose and would have the opportunity that it's easily readable, as most people know how to read JSON. 
But Turtle is stell less verbose, so here would be an extraction of the way how I would put it in RDF.
The URIs using dbpedia.org are of course made up examples.

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix dbp: <http://dbpedia.org/dbp#> .

<http://dbpedia.org/db/Sentence>
	dc:identifier 24;
	dbp:sentenceTopic Fare_gol;
	dbp:words (
		dbp:word [			
			dbp:wordText "In";
			dbp:pos "http://dbpedia.org/pos#pre";
			dbp:lemma "in"
		]
		dbp:word [
			dbp:wordText "totale";
			dbp:pos "http://dbpedia.org/pos#nom";
			dbp:lemma "totale"
		]
		dbp:word [
			dbp:wordText "in";
			dbp:pos "http://dbpedia.org/pos#pre";
			dbp:lemma "in"
		]
		dbp:word [
			dbp:wordText "carriera";
			dbp:pos "http://dbpedia.org/pos#nom";
			dbp:lemma "carriera"
		]
		dbp:word [
			dbp:wordText "disputò";
			dbp:pos "http://dbpedia.org/pos#ver:remo";
			dbp:lemma "disputare"
		]
		...
		dbp:word [
			dbp:wordText "segnando";
			dbp:pos "http://dbpedia.org/pos#ver:geru";
			dbp:lemma "segnare";
			dbp:frameElement "B-LU"

		]
		dbp:word [
			dbp:wordText "10";
			dbp:pos "http://dbpedia.org/pos#num";
			dbp:lemma "@card@";
			dbp:frameElement B-Quantita_Fare_gol
		]
		dbp:word [
			dbp:wordText "reti";
			dbp:pos "http://dbpedia.org/pos#nom";
			dbp:lemma "rete";
			dbp:frameElement I-Quantita_Fare_gol
		]
		dbp:word [
			dbp:wordText ".";
			dbp:pos "http://dbpedia.org/pos#sent";
			dbp:lemma "."
		]

	) .

<http://dbpedia.org/db/Sentence>
	dc:identifier 26;
	dbp:sentenceTopic Fare_go;
	dbp:words (
		...
	) .
```

**Comment by marfox** [comment]
Sure, sorry for the lack of headers in that file.
They are as follows:
- sentence ID
- token ID
- token
- POS tag
- lemma
- frame
- frame element (in IOB format)

**Comment by marfox** [comment]
>  Turtle format is the best way of representation. XML obviously is really verbose, JSON-LD not nearly as verbose and would have the opportunity that it's easily readable, as most people know how to read JSON.

Here you are mentioning different RDF **serializations**, so I think you are addressing a **semantics** problem by discussing **syntax** solutions.
You should focus on how to translate a **model**.
Don't worry about the syntax, once we come up with a good model, then we can generate **any** of those serializations.

**Comment by marfox** [comment]
The previous comment also applies to your example.
I think you made a **syntactic** translation of the classifier output.
DBpedia is **entity-centric**. This means the core nodes of the knowledge base are entities, which in our case correspond to **FEs**, not sentences.

**Comment by fsonntag** [comment]
Thanks for the clarification! Hearing that from you, I can see that I missed the point. I also was a bit confused, as you already stated, these different syntaxes are all compatible.
So taking the first sentence as an example, we could produce an RDF statement like that:
Subject: Fare Gol
Predicate: Quantita
Object: 10 reti
Please correct me, if I'm wrong.
So generally speaking, we can say:
Subject: Frame
Predicate: FE
Object: Token

**Comment by marfox** [comment]
Nope, your example may be OK for a **FE** rather than a frame (that's 
basically what I first suggested in the [idea 
page](http://wiki.dbpedia.org/gsoc2015/ideas#h460-7).
I would model a frame as a **predicate** attached to a **subject** 
entity, e.g., the title of the article where the extraction came from.

**Comment by fsonntag** [comment]
Okay, I see your point, making this issue really not a trivial task. I think I'm getting the point of your approach. Let's take the second sentence as an example, as we have two FEs there. 
We could wrap up all FEs into a new statement, where each FE is represented as a Predicate-Object pair. I'm not sure, which Subject to pick: the frame, the an own FE class or maybe the already used class d0:Activity. I think the second suggestion makes most sense.

Subject: Great SoccerPlayer
Predicate: Fare_gol
Object: {
		Subject: Fare_gol/FE/d0:Activity
			Predicate: quantita
			Object: vinta 1-0
			Predicate: Competizione
			Object: serie A.
}

**Comment by kkasunperera** [comment]
@marfox this is my idea to represent Frame related data in RDF format, this can be produced by writing a script to the training/classification data format. What do you think about this idea?

e.g. sentence id-27 in training data sample - He played 10 games scoring 5 goals with the Vanuatu national football team 


<rdf:RDF
xmlns:SoccerPlayer="http://en.wikipedia.org/wiki/$PLAYER_NAME#">

<rdf:Description
rdf:about="http://en.wikipedia.org/wiki/$PLAYER_NAME#Scoring">
  <SoccerPlayer:Quantity_Scoring> 5 goals </SoccerPlayer:Quantity_Scoring>
</rdf:Description>

</rdf:RDF>

**Comment by marfox** [comment]
@fsonntag, you are basically doing what is called [**reification**](https://en.wikipedia.org/wiki/Reification_(computer_science)#Reification_on_Semantic_Web).
RDF relations are binary, while frames are n-ary. Hence, reification is one possible solution, but introduces an extra node, thus an extra layer of complexity.
Can you go further in your investigation and try to avoid that annoying `Fare_gol/FE/d0:Activity` node? Would that be possible?

@kkasunperera, please no RDF/XML serialization, this is the most verbose one. Also, your example is not valid RDF/XML (parsing returns 0 triples with [raptor](http://librdf.org/raptor/)).

**Comment by fsonntag** [comment]
@marfox You're right, that's the concept of reification. But not the specific RDF reification use, you linked to.

Anyway I did some research and came about [this note](http://www.w3.org/TR/swbp-n-aryRelations/#RDFReification) by W3C on how to define n-ary relationships. And their suggested way is basically the same as mine, except that it's more concrete. They use blank nodes to represent the additional node.
So when it is proposed by the W3C, I think this is the way to go.
To express my example from above in Turtle syntax, naming the player Gomez, it might look like that:

```
:Gomez 
	a	:SoccerPlayer ;
	:shotGoal _:Goal_Shooting_1 .

:_Goal_Shooting_1
	a	:Goal_Shooting ;
	:quantity :won_1-0;
	:in_competition :serie_A .
```
