### ISSUE TITLE
A decision should be made to break ties in CrowdFlower results

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#28]
[This line](../blob/master/crowdflower_results_into_training_data.py#L66) of the `crowdflower_results_into_training_data.py` sets the annotation to the majority vote answer, but then skips it in case of a tie (i.e., no majority).

Change this behavior by randomly breaking the tie.

**Comment by jerryking58** [comment]
Why to break the tie?

**Comment by marfox** [comment]
No, untrusted data is already discarded from the results.
Breaking the tie means we will not skip an annotation in case there is no majority vote.
This will certainly improve the recall, even if it may affect the precision.

**Comment by marfox** [comment]
Branch `unsupervised`, ties are randomly broken
