### ISSUE TITLE
Investigate available annotated data for the soccer domain

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#29]
## DISCLAIMER: this issue is not related to code

The cost of crowdsourcing the training set annotation can be reduced if we find already annotated sentences (with frame information of course) from third-party resources.
You should explore the availability of such data and produce a report.

Thanks to @fsonntag for pointing this out.

**Comment by aaiijmrtt** [comment]
Apart from English, FrameNets also exist in:

1. German [http://coerll.utexas.edu/frames/]
2. Brazilian Portuguese [http://www.ufjf.br/framenetbr/]
3. Swedish [http://spraakbanken.gu.se/eng/swefn]
4. Spanish [http://sfn.uab.es:8080/SFN]
5. Japanese [http://jfn.st.hc.keio.ac.jp/index.html]
6. Chinese [http://www.cs.ust.hk/~hltc/BiFrameNet/]
