### ISSUE TITLE
Find existing frames that fit into the soccer domain

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#30]
## DISCLAIMER: this issue is not related to code

Produce a list of already available frame candidates (i.e., *frame + frame elements + example sentences*) that would fit well into the soccer domain.
You should proceed in either ways, with 2 opposite paradigms in mind.
- *top-down*: you look for suitable **frames** in a frame repository;
- *bottom-up*: you start from the **top-ranked lexical units** as per the output of [step 2](../../fact-extractor#high-level-workflow--related-code) and look for suitable ones in a frame repository.

Here are 2 frame repos as a starting point:
- [FrameNet](https://framenet.icsi.berkeley.edu/fndrupal/index.php?q=frameIndex)
- [Kicktionary](http://kicktionary.de/Scenario_Overview.html)

**Comment by aaiijmrtt** [comment]
some FrameNet frames that may be used in the soccer domain are as follows [from https://framenet.icsi.berkeley.edu/fndrupal/index.php?q=frameIndex]:

1. Beat_opponent
2. Defending
3. Dominate_competitor
4. Dominate_situation
5. Domination
6. Event
7. Event_instance
8. Finish_competition
9. Finish_game
10. Hit_or_miss
11. Hit_target
12. Intercepting
13. Location_in_time
14. Lose_possession
15. Lose_possession_scenario
16. Passing
17. Path_shape
18. Practice
19. Preventing
20. Team
21. Win_prize
