### ISSUE TITLE
Merge chunks on common words

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#38]
Consider the following sentence:
> Ha giocato per quattro anni nella massima serie scozzese con il Dundee.

[This script](../blob/chunk-combo/combine_chunks.py) combines 3 chunking strategies, and yields the following set of chunks for the given sentence:
```
set([u'quattro', u'massima serie', u'serie scozzese', u'anni', u'Dundee'])
```
Currently, overlap among the chunkers output is only handled at substring/superstring level.
We should also merge chunks on common words.
The output should be:
```
set([u'quattro', u'massima serie scozzese', u'anni', u'Dundee'])
```

**Comment by e-dorigatti** [comment]
Hello Marco, which files are we supposed to use as input for the script? Can you please include them in the resources folder?

**Comment by marfox** [comment]
Done

**Comment by e-dorigatti** [comment]
I cannot reproduce the problem, the chunks for that sentence are `set([u'quattro anni', u'serie scozzese', u'massima', u'il Dundee'])`.

I had to make minor changes so that the script runs successfully but I don't think they are the cause for this, here's the diff:

```
@@ -11,7 +11,7 @@ import stopwords
 from collections import defaultdict
 
 debug = True
-all_chunks = {}
+all_chunks = defaultdict(lambda: dict())
 
 # From https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Longest_common_substring#Python2
 def longest_common_substring(s1, s2):
@@ -92,7 +93,7 @@ for sentence_id, values in all_chunks.iteritems():
     # If chunks overlap, prefer links > ngrams > chunker
     link_chunks = values['twm-links']
     ngram_chunks = values['twm-ngrams']
-    tp_chunks = values['textpro-chunks']
+    tp_chunks = values.get('textpro-chunks', set())
     if debug:
         print 'LINKS'
         print link_chunks
```

**Comment by marfox** [comment]
I may have uploaded a wrong version of the files.
Try now

**Comment by marfox** [comment]
There's something weird: I can reproduce the issue under Linux, but not 
under Mac.

**Comment by marfox** [comment]
The only difference on the 2 machines is the Python version: 2.7.8 under 
Linux VS 2.7.9 under Mac

**Comment by fsonntag** [comment]
@e-dorigatti How do you start the script? You just have to give it ```resources/``` as a parameter.
I also had to fix the script in order to get it running. Maybe ```os.walk()``` works different on different operating systems or Python versions.
The fix I made in the commit 3e93667 should make it work independent from your configuration.

**Comment by e-dorigatti** [comment]
Perhaps there's some sort of undefined behavior somewhere.  I get the same results using python 2.7.6 and python 3.4.0, under ubuntu 14.04

@fsonntag yes, I start it like that. We both made equivalent changes to get it running

**Comment by marfox** [comment]
Try to coordinate as much as possible guys and keep up with the great work!
It's fair enough by now if you can fix the issue using the OS that works.
Please keep track of this (yet another) platform-related issue.

**Comment by e-dorigatti** [comment]
Marco, I am working on it but results are not perfect in many cases and I think this is due to the priorities between the chunk sources. I added my changes to [this commit](https://github.com/e-dorigatti/fact-extractor/commit/79648ff832c51c246ea8cf2be7f0eea6ceddd845), what do you think can be improved?

**Comment by marfox** [comment]
I had a look at the output, it seems you have fixed the example and other sentences, which is already a big improvement.
If you fire a pull request for this issue, I think it's fair enough.

A big improvement would be to merge all the contiguous chunks into a big single one, I'll open another issue for that.

**Comment by marfox** [comment]
See #40

**Comment by e-dorigatti** [comment]
Okay. Btw I managed to make the script work on my laptop, can you check if it works both on your Linux and your Mac?

**Comment by marfox** [comment]
Works like a charm
