### ISSUE TITLE
Normalize Date Expressions before classification

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#42]
Lots of FEs are dates:
- *absolute*, e.g., `May 2008`
- *relative*, e.g., `the previous season`
- *interval*, e.g., `from 2008 to 2015`

A normalizer based on [this CFG grammar](../blob/date-normalizer/date_normalizer/DateAndTime.g4) should be implemented at sentence pre-processing time.
It is written as an [ANTLR grammar](https://theantlrguy.atlassian.net/wiki/display/ANTLR4/Grammar+Lexicon).

**Comment by Warun26** [comment]
Hi @marfox ,
I think the link to the CFG is not working. Also, just out of curiosity, I wanted to know what advantages CFGs offer over rule based systems such as SUTime(used in stanfordNLP). I am guessing there will be a lot of rules when we consider different languages but is that the only disadvantage?

Thanks in advance.
Varun

**Comment by marfox** [comment]
Sorry for the broken link @Warun26 , the grammar has moved to a new module in the meanwhile. It should be fixed now.
CFG is a rule-based system, and as such behaves the same as SUTime.
In addition, it also allows for **recursive** rules, and I'm not sure if this is possible with SUTime, is it?

**Comment by Warun26** [comment]
SUTime does not support recursive rules. It just applies basic regex rules over tokens to extract temporal data. Thanks for the information! :-)

**Comment by marfox** [comment]
Should implement the behavior in #47
