### ISSUE TITLE
Automatically annotate numerical FEs

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#47]
Here is a (non-exhaustive) summary of the expressions we want to annotate automatically and transform into standard **XML Schema Datatypes** (xsd), such as [dates](http://www.w3schools.com/schema/schema_dtypes_date.asp).
We decided that the easiest strategy is to implement a set of regexes.

**Heads-up**: relative expressions should be resolved against an absolute date (e.g., `$YEAR`), but that's a hard one. `$YEAR` should take a default value `year` if no absolute date is found.

#### Tempo (Time)
Input | Output
--------- | --------- 
il 14 settembre 2010 | "2010-09-14"^^xsd:date
il 15 ottobre | "10-15"^^xsd:gMonthDay
nel giugno 2012 | "2012-06"^^xsd:gYearMonth
in maggio | "05"^^xsd:gMonth
nel 2014 | "2014"^^xsd:gYear
l'anno seguente | "$YEAR + 1" (plain literal)

#### Durata (Duration)
Input | Output
--------- | ---------
 stagione 1984-1985 | "P1Y"^^xsd:duration 
campionato 1921-1922 | "P1Y"^^xsd:duration
fino al 1999 | "to 1999" (plain literal)
per due stagioni |  "P2Y"^^xsd:duration
per due anni | "P2Y"^^xsd:duration
dal 1996 al 2005 | "P9Y"^^xsd:duration
una sola stagione | "P1Y"^^xsd:duration

#### Punteggio (Score)
Input | Output
--------- | ---------
2-1 | "2-1" (plain literal)

#### Classifica (Ranking)
Input | Output
--------- | ---------
primo | "I" (roman numeral, plain literal)

**Comment by e-dorigatti** [comment]
@marfox I am almost satisfied with this but while testing I found some cases which I don't know how to handle:
 - nell'estate del 2006 / fino all'estate del 2006: do we want to handle seasons of the year? Or should I classify this as a normal year (i.e. `"2006"^^:gYear`/`to 2006`)?
 - Bekker gioca per il \<team\> dal 2013: since there is "fino al" it would make sense to have "dal" as well and transform it to something like `from <year>`
 - negli anni ottanta: I am not sure how to transform this, `"P10Y"^^xsd:duration` maybe?
 - nell'amichevole del 10 febbraio 2010: this is currently not matched, but it probably should right?

**Comment by e-dorigatti** [comment]
Here's an example of annotated sentence:
```
30	0	Ha	VER:pres	avere	Attività	O
30	1	esordito	VER:pper	esordire	Attività	O
30	2	con	PRE	con	Attività	O
30	3	la	DET:def	il	Attività	O
30	4	Nazionale cipriota	ENT	Nazionale cipriota	Attività	B-Squadra_Attività
30	5	nel 1991	"1991"^^xsd:gYear	nel 1991	Attività	B-Tempo_Attività
30	6	,	PON	,	Attività	O
30	7	giocando	VER:geru	giocare	Attività	B-LU
30	8	41	NUM	@card@	Attività	O
30	9	partite	NOM	partita	Attività	O
30	10	fino al 1997	"to 1997"	fino al 1997	Attività	B-Durata_Attività
```

@marfox how does it look?

**Comment by marfox** [comment]
On 6/25/15 4:31 PM, Emilio Dorigatti wrote:
> @marfox <https://github.com/marfox> I am almost satisfied with this but
> while testing I found some cases which I don't know how to handle:
>
>   * nell'estate del 2006 / fino all'estate del 2006: do we want to
>     handle seasons of the year? Or should I classify this as a normal
>     year (i.e. |"2006"^^:gYear|/|to 2006|)?
Normal year
>   * Bekker gioca per il <team> dal 2013: since there is "fino al" it
>     would make sense to have "dal" as well and transform it to something
>     like |from <year>|
It makes sense
>   * negli anni ottanta: I am not sure how to transform this,
>     |"P10Y"^^xsd:duration| maybe?
Sure go ahead
>   * nell'amichevole del 10 febbraio 2010: this is currently not matched,
>     but it probably should right?
Sure

**Comment by marfox** [comment]
Looks pretty good.
One thing I forgot to mention:
the output datatypes will appear in the final dataset, while here you can just copy the n-gram (like we did in other ENTs)
