### ISSUE TITLE
The subject should be the article URI from which the fact was extracted

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#49]
Currently, we don't keep track of the sentences provenance (i.e., the Wikipedia article).
A sample extracted fact now looks like:
```
resource:SENTENCE0000 fact:Attività fact:Attività0000 .
```
We only keep track of the sentence ID from which the fact was extracted.
Instead, we should link to the Wikipedia article containing that sentence:
```
resource:${WIKIPEDIA_ARTICLE} fact:Attività fact:Attività0000 .
```

**Comment by marfox** [comment]
The [WikiExtractor](../blob/master/lib/WikiExtractor.py) remembers the URL of the article.
Such information should be passed to [this script function](../blob/unsupervised/produce_labeled_data.py#L160), which also produces the dataset from the unsupervised method.

**Comment by e-dorigatti** [comment]
This works supposing that file names are used as sentence ID in the format `wikiID.uniqID` and that there exists a mapping from wiki ID to the title of the article. This is completely handled in [this new file](../blob/unsupervised/extract-sentences.sh) which creates file names according to this rule and the mapping itself
