### ISSUE TITLE
Validate crowdsourced gold standard (part 2)

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#51]
Check and curate the annotations obtained from CrowdFlower, transformed into training data format.
[Part 2](../blob/unsupervised/resources/gold-standard02).
Save to a new file with extension = `.curated`

**Comment by marfox** [comment]
Could you please give updates on this task status, @e-dorigatti ?

**Comment by e-dorigatti** [comment]
@marfox I'm starting to work on it now

**Comment by e-dorigatti** [comment]
Done. Given my performances on crowdflower I'm not sure how reliable is my review.. I left my comments in a new column

**Comment by marfox** [comment]
I'll go ahead with #53 , please do so with #52 and feel free to close this one
