### ISSUE TITLE
Refactor, clean and organize the code base

### ISSUE THREAD

**Issue by e-dorigatti** [dbpedia/fact-extractor#55]
Currently there are a bunch of scripts floating around, it's time to clean up and organize them in some way. Merge the `date-normalizer` and `unsupervised` branches into `master`, while the `no-chunker` and `chunk-combo` are leftovers from failed experiments, so leave them be.

TODOs:
 - [x] Extract relevant data from the wikipedia dump (articles and soccer player pages)
 - [x] Rank verbs and extract the most significant ones
 - [x] Interfacing with crowdflower (create input sentences (aka gold) and interface, parse results)
 - [x] Unsupervised training
 - [x] Seed selection and sentence splitting
 - [x] Launch classifier jobs (training etc.)

Other Ideas:
 - Makefile is becoming too big and with different rules related to the same job, [split into multiple makefiles](https://www.gnu.org/software/make/manual/html_node/Include.html)

**Comment by e-dorigatti** [comment]
Kept a copy of `combine_chunks.py` [here](https://gist.github.com/e-dorigatti/8392e12d587b75d69d74)

**Comment by marfox** [comment]
Please remember to adapt all the relative imports and resources paths

**Comment by e-dorigatti** [comment]
Unsupervised and crowdflower targets are not complete as they rely on an external repository which performs entity linking. The linked sentences should be placed in the `../linked` directory relative to the Makefile
