### ISSUE TITLE
Add a flexible command line to the supervised classifier run script

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#66]
[This script](../blob/master/supervised/italian_train_and_run.sh) is in charge of various tasks related to the supervised classifier.
Currently, it only parses positional command line arguments, but some of them are optional.

The script should be able to perform the following tasks, separately:
1. Train
2. Run, interactive mode
3. Run, batch mode
4. Evaluate against gold

Implement a standard command line parser.

**Comment by e-dorigatti** [comment]
Creating appropriate rules in the makefile instead
