### ISSUE TITLE
Translate sample CrowdFlower results into training data format

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#7]
Implement step 4.i of the workflow, as per the [README](../blob/master/README.md#high-level-workflow--related-code).
You should review the related script and make it more robust.
In other words:
1. parametrize hard-coded items
2. add function docstrings
3. add descriptive comments
4. implement a solid command-line with the `argparse` module

Use the following samples as input:
1. [CrowdFlower results](../blob/master/resources/crowdflower-results.sample)
2. [TreeTagger output directory](../blob/master/resources/treetagger-output-sample)

**Comment by jerryking58** [comment]
Hi, I am trying this task and not clear about training data format due to the Italian sample. Can you explain the features you selected to be trained?

**Comment by marfox** [comment]
Hi, don't worry about the features, it is a syntactic transformation we 
are performing here.
You just need to comply with the sample output syntax, this is language 
independent. Imagine that instead of tokens and lemmas in Italian, there 
could be any language (supported by TreeTagger) there.

**Comment by fsonntag** [comment]
Just a short question, is this issue still up to date? It looks like except the parameterization everything is already done.

**Comment by marfox** [comment]
It's still open for you to get acquainted with the code and the concepts behind
