### ISSUE TITLE
Keep track of the SVM probability score

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#70]
You should first locate the class where **libsvm** is used.
Then, you should activate the **flag** for computing the probability score (if not already done).
Finally, you should store it at classification runtime.

**Comment by e-dorigatti** [comment]
I always get a probability of 0.0 for all the classes (straight output from `svm_predict_probability`)
@marfox can you confirm?

**Comment by e-dorigatti** [comment]
As it turned out `-b 1` needs to be provided to svm-train to enable probability the computation during classification. (see the [libsvm](https://www.csie.ntu.edu.tw/~cjlin/libsvm/) page)
