### ISSUE TITLE
Lexical Units (LUs) with more than 1 token are not handled

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#8]
[This script](../blob/master/crowdflower_results_into_training_data.py) takes as input:
1. a *CSV* file containing CrowdFlower annotation results
2. a directory with TreeTagger output files, 1 sentence per file
and translates it into *IOB* format to be fed to a classifier.
See #7 for more details on how to run the script.

You should fix a bug introduced in [these lines](../blob/master/crowdflower_results_into_training_data.py#L79-L82): **if the LU is composed of more than 1 token, the remaining ones are not handled** (i.e., there will be no `I-` tag assignment).

**Comment by e-dorigatti** [comment]
Hello Marco, I am working on this. I would like to test my work but in the resources folder there aren't LUs with more than one token and the workflow extracting verbs is taking ages to complete. Could you please give me some examples of LU with more than one token or some hints about where to find them?

**Comment by marfox** [comment]
Hi @e-dorigatti,
It seems you picked the hardest warm-up task :8ball:

Typical LUs with more than one token are English phrasal verbs like `keep up` or `stand out`.
The LUs provided in the `resources` folder are in Italian.
I do not expect to find many multiple-token LUs in that language, but it would be cool to verify.
You definitely need to dig into the extracted verbs output for that.
