### ISSUE TITLE
Add a flag to toggle numerical FEs evaluation

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#81]

**Comment by e-dorigatti** [comment]
The two fixes, for [unsupervised](https://github.com/dbpedia/fact-extractor/commit/ca46a79db507eb4f26984e4944bf9ba14e272092) and [supervised](https://github.com/dbpedia/fact-extractor/commit/e4d02a1c4ee07cc69c641aaa49dfc9e620f188c7), are located on two different brances so careful when merging!
