### ISSUE TITLE
Review code documentation

### ISSUE THREAD

**Issue by marfox** [dbpedia/fact-extractor#83]
- [x] README - update workflow with Makefile instructions
- [x] complete README
- [ ] function docstrings

**Comment by marfox** [comment]
@e-dorigatti, what is the status of the docstrings?

**Comment by e-dorigatti** [comment]
I [committed](https://github.com/dbpedia/fact-extractor/commit/e8652e7816c679495fb2de0c2f8a89697f874162) some descriptions about most of the scripts that we have, except for the verb ranking part as I didn't really know what to write. Is it enough?

**Comment by marfox** [comment]
That's okay for the header docstrings, but can you document the **function** docstrings as well please?

**Comment by marfox** [comment]
@e-dorigatti, let me know when I can close this one.

**Comment by e-dorigatti** [comment]
@marfox you can close this.

**Comment by marfox** [comment]
Hey @e-dorigatti , it would be best to add [field lists](http://sphinx-doc.org/domains.html#info-field-lists) to docstrings.
In this way, we can generate proper documentation sites using modules like [Sphinx](http://sphinx-doc.org/index.html).
See also http://docutils.sourceforge.net/docs/user/rst/quickref.html and http://docs.python-guide.org/en/latest/writing/documentation/
